### ISSUE TITLE
Training cost of track prediction model

### ISSUE THREAD

**Issue by ziyin-xiong** [homangab/Track-2-Act#1]
Hello! I am currently attempting to reproduce your work on track prediction. I'm wondering if you could kindly share some details of the training costs involved in the track prediction task, such as the number of gpus required, training duration, batch size, and other pertinent information.

**Comment by hnuzhy** [comment]
I'm also looking forward to know more details of the training cost. For example, how much time will it take if I use 4 A100 (80GB/per) GPUs?

**Comment by homangab** [comment]
Hello, Thanks for the questions! And apologies for my very late response. For this work, I used 8 A100s (80GB per gpu) with a batch size of 256 and the training duration was around 72 hours.

**Comment by ziyin-xiong** [comment]
> Hello, Thanks for the questions! And apologies for my very late response. For this work, I used 8 A100s (80GB per gpu) with a batch size of 256 and the training duration was around 72 hours.

Thanks for your reply!

**Comment by ziyin-xiong** [comment]
Thanks for your reply!
