### ISSUE TITLE
How to get the goal image when doing evaluation?

### ISSUE THREAD

**Issue by hnuzhy** [homangab/Track-2-Act#3]
Hi, thanks a lot for releasing the source code of your excellent work. After reading the paper, I found that it did not explain how can we obtain the goal image for a specifical task when running real robot evaluations. Is it not a necessary condition for the final closed-loop deployment when inferring the Residual Policy Correction network? Thus, it can be removed during inference. I'm looking forward to your reply.

**Comment by homangab** [comment]
Thanks for the question about goal image! In this work, we use the goal image to specify a task. For evaluation, we do need to obtain the goal image by intervening in the scene (i.e. if we want the robot to execute a task of opening the door, we need to open the door and obtain the image through the robot's camera).  The idea is similar to any goal-conditioned policy learning (where goals can be images, language etc. - in this work, the goals are images)
