### ISSUE TITLE
What do the 4 dimensions of data['action'] of the traing data represent ?

### ISSUE THREAD

**Issue by Magi329** [homangab/Track-2-Act#4]
Hi,
I am trying to reproduce your work, and I'd like to know what are the four dimensions of data['action'].

If possible, could you please give a more detailed description of the structure of the training data?

Thanks a lot^^
Magi

**Comment by homangab** [comment]
Thanks for the question. I am copying my response from email below:

The training data is about point tracks (obtained by running Co-Tracker on videos) and the dimensions represent (batch_size, horizon length of video, number of points tracked, 2) the 2 is for (x,y) coordinates. Hope this is helpful.
